/**
 * Loads real jewelry part-asset images into JewelryPartOption, once they exist. This is
 * a manifest-driven loader, not a source of fake data — the actual band/setting/stone
 * images are supplied separately (see the plan's "part assets sourced separately"
 * decision), not generated by this script.
 *
 * Reads jewelry-parts-manifest.json (gitignored, per-environment) from the project
 * root. See jewelry-parts-manifest.example.json for the expected shape:
 * [{ id, category, partType, label, imageUrl, slot: {left,top,width,height}, sortOrder? }]
 *
 * Run: npm run db:seed-jewelry-parts
 */
import { config } from "dotenv";
config({ path: ".env.local" });

import { existsSync, readFileSync } from "fs";
import { join } from "path";

import { PrismaClient } from "@prisma/client";

const MANIFEST_PATH = join(process.cwd(), "jewelry-parts-manifest.json");

type ManifestEntry = {
  id: string;
  category: string;
  partType: string;
  label: string;
  imageUrl: string;
  slot: { left: number; top: number; width: number; height: number };
  sortOrder?: number;
};

async function main() {
  if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not set");

  if (!existsSync(MANIFEST_PATH)) {
    console.log(
      `No jewelry-parts-manifest.json found at ${MANIFEST_PATH} — nothing to seed.\n` +
        "Copy jewelry-parts-manifest.example.json to jewelry-parts-manifest.json and fill in real part images to populate the configurator."
    );
    return;
  }

  const entries: ManifestEntry[] = JSON.parse(readFileSync(MANIFEST_PATH, "utf-8"));
  const db = new PrismaClient();

  for (const entry of entries) {
    await db.jewelryPartOption.upsert({
      where: { id: entry.id },
      create: {
        id: entry.id,
        category: entry.category,
        partType: entry.partType,
        label: entry.label,
        imageUrl: entry.imageUrl,
        slot: entry.slot,
        sortOrder: entry.sortOrder ?? 0,
        isActive: true,
      },
      update: {
        category: entry.category,
        partType: entry.partType,
        label: entry.label,
        imageUrl: entry.imageUrl,
        slot: entry.slot,
        sortOrder: entry.sortOrder ?? 0,
        isActive: true,
      },
    });
    console.log(`Seeded ${entry.label} (${entry.category}/${entry.partType})`);
  }

  await db.$disconnect();
  console.log(`\nJewelry parts seed complete (${entries.length} options).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
